#环境准备
#redis
#jnacos

version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime"
  jnacos:
    image: jnacos
    ports:
      - "8848:8848"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/logs/nacos/:/nacos/logs"
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - "/etc/localtime:/etc/localtime"
     - "/opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
     - "/opt/nginx/logs:/var/log/nginx"