server:
  port: 2100
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    # 路由网关配置
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
       - id: static
         uri: lb://platform
         order: 10000
         predicates:
         - Path=/**
      httpclient:
        connect-timeout: 20000
  main:
      allow-bean-definition-overriding: true
ace:
  config:
    openMongoDB: false
    localRecord: true
    sso:
      open: false
      completedValidateUrl: ""
      validateUrl: ""
      onlyOneApp: false
      appName: ""
# 加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.boot.actuate.redis: error