CREATE TABLE SYS_CACHE_DATA
(
ID          VARCHAR2(400 BYTE) NOT NULL,
VALUE       CLOB,
EXPIRE_TIME DATE
);
COMMENT ON TABLE SYS_CACHE_DATA IS '系统缓存数据';
COMMENT ON COLUMN SYS_CACHE_DATA.EXPIRE_TIME IS '过期时间';
COMMENT ON COLUMN SYS_CACHE_DATA.ID IS '主键';
COMMENT ON COLUMN SYS_CACHE_DATA.VALUE IS '值';

CREATE UNIQUE INDEX SYS_CACHE_DATA_PK ON SYS_CACHE_DATA
(ID)
LOGGING
;
