zuul:
    routes:
        dv-testapp-platform:              #  路由 id 自定义
            path: /dv-testapp-platform/**   # 配置请求 url 的映射路径
            url: http://127.0.0.1:8083/
#        cd-jari716oa:
#            path: /cd-jari716oa/**
#            url: http://127.0.0.1:8813/
#        dv-testapp-platform: #  路由 id 自定义
#            path: /zzj-testflow/**   # 配置请求 url 的映射路径
#            url: http://127.0.0.1:8083/
#        aa-test: #  路由 id 自定义
#            path: /aa-test/**   # 配置请求 url 的映射路径
#            url: http://127.0.0.1:8816/
    sensitive-headers: Access-Control-Allow-Origin
    ignored-headers: Access-Control-Allow-Origin

ace:
    config:
        isDevState: 1
spring:
    redis:
        #open: true  # 是否开启redis缓存  true开启   false关闭
        database: 3
        host: 192.168.19.8
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5  # 连接池中的最小空闲连接

