server:
  port: 3200
spring:
#  redis:
#      #open: true  # \u662F\u5426\u5F00\u542Fredis\u7F13\u5B58  true\u5F00\u542F   false\u5173\u95ED
#      database: 0
#      host: 192.168.19.8
#      port: 6379
#      password:    # \u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
#      timeout: 6000ms  # \u8FDE\u63A5\u8D85\u65F6\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
#      jedis:
#        pool:
#          max-active: 1000  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
#          max-wait: -1ms      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
#          max-idle: 10      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
#          min-idle: 5  # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//192.168.16.175:1521/JARIORA
#    username: acelicense
#    password: jarisoft
    driverClassName: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.19.9:5236:JARIACELICENSE
    username: JARIACELICENSE
    password: jarisoft11
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
              #validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
                  #login-username: admin
                  #login-password: admin
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: false
      wall:
        config:
          multi-statement-allow: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.csicit.ace.common.pojo.domain
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 0
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 2
    #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    db-column-underline: true
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh-mapper: true
    #\u6570\u636E\u5E93\u5927\u5199\u4E0B\u5212\u7EBF\u8F6C\u6362
    capital-mode: true
    #\u5E8F\u5217\u63A5\u53E3\u5B9E\u73B0\u7C7B\u914D\u7F6E
    #key-generator: com.baomidou.springboot.xxx
    #\u903B\u8F91\u5220\u9664\u914D\u7F6E
    logic-delete-value: -1
    logic-not-delete-value: 0
    #\u81EA\u5B9A\u4E49\u586B\u5145\u7B56\u7565\u63A5\u53E3\u5B9E\u73B0
    #meta-object-handler: com.baomidou.springboot.xxx
    #\u81EA\u5B9A\u4E49SQL\u6CE8\u5165\u5668
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
