CREATE TABLE "WFD_USER_PAGE"
(
"ID" VARCHAR2(50) NOT NULL,
"USER_ID" VARCHAR2(50) NOT NULL,
"WFD_ID" VARCHAR2(50) NOT NULL,
"PAGE_SIZE" INTEGER NOT NULL  DEFAULT 10,
"ARG1" VARCHAR2(50),
"ARG2" VARCHAR2(50),
"ARG3" VARCHAR2(50),
"PAGE_CODE" VARCHAR2(50));

alter table WFD_USER_PAGE add primary key("ID");

COMMENT ON TABLE "WFD_USER_PAGE" IS '用户默认流程页面';
COMMENT ON COLUMN "WFD_USER_PAGE"."USER_ID" IS '用户主键';
COMMENT ON COLUMN "WFD_USER_PAGE"."WFD_ID" IS '流程定义主键';
COMMENT ON COLUMN "WFD_USER_PAGE"."ID" IS '主键';
COMMENT ON COLUMN "WFD_USER_PAGE"."PAGE_CODE" IS '默认流程页面标识';
COMMENT ON COLUMN "WFD_USER_PAGE"."PAGE_SIZE" IS '默认每页数量';
COMMENT ON COLUMN "WFD_USER_PAGE"."ARG1" IS '预留属性1';
COMMENT ON COLUMN "WFD_USER_PAGE"."ARG2" IS '预留属性2';
COMMENT ON COLUMN "WFD_USER_PAGE"."ARG3" IS '预留属性3';

CREATE TABLE "WFI_USER_TASK_STATE"
(
"ID" VARCHAR(50) NOT NULL,
"TASK_ID" VARCHAR2(50) NOT NULL,
"USER_ID" VARCHAR2(50) NOT NULL,
"STATE" VARCHAR2(50) NOT NULL) ;

alter table WFI_USER_TASK_STATE add primary key("ID");

COMMENT ON TABLE "WFI_USER_TASK_STATE" IS '用户任务办理状态';
COMMENT ON COLUMN "WFI_USER_TASK_STATE"."STATE" IS '办理状态';
COMMENT ON COLUMN "WFI_USER_TASK_STATE"."ID" IS '主键';
COMMENT ON COLUMN "WFI_USER_TASK_STATE"."TASK_ID" IS '任务主键';
COMMENT ON COLUMN "WFI_USER_TASK_STATE"."USER_ID" IS '用户主键';