CREATE TABLE WFD_FLOW_CATEGORY
(
ID VARCHAR2(50) NOT NULL,
NAME VARCHAR2(100),
SORT_NO INT,
APP_ID VARCHAR2(50));
COMMENT ON TABLE WFD_FLOW_CATEGORY IS '流程类别';
COMMENT ON COLUMN WFD_FLOW_CATEGORY.APP_ID IS '应用ID';
COMMENT ON COLUMN WFD_FLOW_CATEGORY.ID IS '主键';
COMMENT ON COLUMN WFD_FLOW_CATEGORY.NAME IS '类别名称';
COMMENT ON COLUMN WFD_FLOW_CATEGORY.SORT_NO IS '序号';

CREATE TABLE WFD_FLOW
(
ID VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
CODE VARCHAR2(50),
SORT_NO INT DEFAULT 1,
CATEGORY_ID VARCHAR2(50),
DESCRIPTION VARCHAR2(4000),
ADMIN_AUTH_ID VARCHAR2(50),
QUERY_AUTH_ID VARCHAR2(50),
HAS_MODIFIED NUMBER(1,0) DEFAULT 0,
REVISE_VERSION INT DEFAULT 0,
MODEL CLOB,
FORM_DATA_TABLE VARCHAR2(50),
FORM_DATA_SOURCE_ID VARCHAR2(50),
IS_EDITING NUMBER(1,0) DEFAULT 0,
EDITING_USER VARCHAR2(50),
LAST_EDIT_TIME DATE,
INIT_AUTH_ID VARCHAR2(50),
SEQ_NO INT DEFAULT 0 NOT NULL,
LATEST_CREATE_TIME DATE,
APP_ID VARCHAR2(50));
COMMENT ON TABLE WFD_FLOW IS '流程定义';
COMMENT ON COLUMN WFD_FLOW.ADMIN_AUTH_ID IS '监控权限';
COMMENT ON COLUMN WFD_FLOW.APP_ID IS '应用id';
COMMENT ON COLUMN WFD_FLOW.CATEGORY_ID IS '流程类别';
COMMENT ON COLUMN WFD_FLOW.CODE IS '流程标识';
COMMENT ON COLUMN WFD_FLOW.DESCRIPTION IS '描述信息';
COMMENT ON COLUMN WFD_FLOW.EDITING_USER IS '编辑用户';
COMMENT ON COLUMN WFD_FLOW.FORM_DATA_SOURCE_ID IS '数据源id';
COMMENT ON COLUMN WFD_FLOW.FORM_DATA_TABLE IS '数据表名';
COMMENT ON COLUMN WFD_FLOW.HAS_MODIFIED IS '发布后已经修改过';
COMMENT ON COLUMN WFD_FLOW.ID IS '主键';
COMMENT ON COLUMN WFD_FLOW.INIT_AUTH_ID IS '发起权限';
COMMENT ON COLUMN WFD_FLOW.IS_EDITING IS '是否在编辑';
COMMENT ON COLUMN WFD_FLOW.LAST_EDIT_TIME IS '最后编辑时间';
COMMENT ON COLUMN WFD_FLOW.LATEST_CREATE_TIME IS '最新创建时间';
COMMENT ON COLUMN WFD_FLOW.MODEL IS '流程模型';
COMMENT ON COLUMN WFD_FLOW.NAME IS '流程名称';
COMMENT ON COLUMN WFD_FLOW.QUERY_AUTH_ID IS '查询权限';
COMMENT ON COLUMN WFD_FLOW.REVISE_VERSION IS '修订版本号';
COMMENT ON COLUMN WFD_FLOW.SEQ_NO IS '流水号';
COMMENT ON COLUMN WFD_FLOW.SORT_NO IS '流程序号';

CREATE TABLE WFD_FLOW_AGENT
(
ID VARCHAR2(50) NOT NULL,
BEGIN_TIME DATE,
END_TIME DATE,
ENABLED NUMBER(1,0) DEFAULT 1,
FLOW_ID VARCHAR2(50),
ORIGIN_USER_ID VARCHAR2(50),
AGENT_USER_ID VARCHAR2(50),
AGENT_USER_NAME VARCHAR2(50));
COMMENT ON TABLE WFD_FLOW_AGENT IS '工作代办规则';
COMMENT ON COLUMN WFD_FLOW_AGENT.AGENT_USER_ID IS '代办用户ID';
COMMENT ON COLUMN WFD_FLOW_AGENT.AGENT_USER_NAME IS '代办用户名称';
COMMENT ON COLUMN WFD_FLOW_AGENT.BEGIN_TIME IS '启用时间';
COMMENT ON COLUMN WFD_FLOW_AGENT.ENABLED IS '是否启用0不，1启用';
COMMENT ON COLUMN WFD_FLOW_AGENT.END_TIME IS '结束时间';
COMMENT ON COLUMN WFD_FLOW_AGENT.FLOW_ID IS '流程';
COMMENT ON COLUMN WFD_FLOW_AGENT.ORIGIN_USER_ID IS '原用户ID';

CREATE TABLE WFD_GLOBAL_RULE
(
ID VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50),
DESCRIPTION VARCHAR2(2000),
EXPRESSION CLOB,
APP_ID VARCHAR2(50));
COMMENT ON TABLE WFD_GLOBAL_RULE IS '全局规则表';
COMMENT ON COLUMN WFD_GLOBAL_RULE.APP_ID IS '应用ID';
COMMENT ON COLUMN WFD_GLOBAL_RULE.DESCRIPTION IS '规则描述';
COMMENT ON COLUMN WFD_GLOBAL_RULE.EXPRESSION IS '表达式';
COMMENT ON COLUMN WFD_GLOBAL_RULE.ID IS '主键';
COMMENT ON COLUMN WFD_GLOBAL_RULE.NAME IS '规则名称';


CREATE TABLE WFD_GLOBAL_VARIANT
(
ID VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50),
CAPTION VARCHAR2(100),
DATA_TYPE VARCHAR2(50),
VALUE_EXPRESSION VARCHAR2(100),
APP_ID VARCHAR2(50),
DEFAULT_VALUE VARCHAR2(100)) ;
COMMENT ON TABLE WFD_GLOBAL_VARIANT IS '全局变量表';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.APP_ID IS '应用ID';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.CAPTION IS '变量标题';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.DATA_TYPE IS '类型';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.DEFAULT_VALUE IS '初始值';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.ID IS '主键';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.NAME IS '变量名';
COMMENT ON COLUMN WFD_GLOBAL_VARIANT.VALUE_EXPRESSION IS '取值表达式';


CREATE TABLE WFD_V_FLOW
(
ID VARCHAR2(50) NOT NULL,
FLOW_VERSION INT,
NAME VARCHAR2(50) NOT NULL,
CODE VARCHAR2(50),
SORT_NO INT,
CATEGORY_ID VARCHAR2(50),
DESCRIPTION VARCHAR2(4000),
ADMIN_AUTH_ID VARCHAR2(50),
QUERY_AUTH_ID VARCHAR2(50),
FLOW_ID VARCHAR2(50),
IS_LATEST NUMBER(1,0),
MODEL CLOB,
BPMN CLOB,
FORM_DATA_TABLE VARCHAR2(50),
FORM_DATA_SOURCE_ID VARCHAR2(50),
INIT_AUTH_ID VARCHAR(50),
VERSION_BEGIN_DATE DATETIME(6),
VERSION_END_DATE DATETIME(6),
IS_USED NUMBER(1,0));
COMMENT ON TABLE WFD_V_FLOW IS '流程定义';
COMMENT ON COLUMN WFD_V_FLOW.ADMIN_AUTH_ID IS '监控权限';
COMMENT ON COLUMN WFD_V_FLOW.BPMN IS 'BPMN';
COMMENT ON COLUMN WFD_V_FLOW.CATEGORY_ID IS '流程类别';
COMMENT ON COLUMN WFD_V_FLOW.CODE IS '流程标识';
COMMENT ON COLUMN WFD_V_FLOW.DESCRIPTION IS '描述信息';
COMMENT ON COLUMN WFD_V_FLOW.FLOW_ID IS '流程id';
COMMENT ON COLUMN WFD_V_FLOW.FLOW_VERSION IS '版本';
COMMENT ON COLUMN WFD_V_FLOW.FORM_DATA_SOURCE_ID IS '数据源id';
COMMENT ON COLUMN WFD_V_FLOW.FORM_DATA_TABLE IS '数据表名';
COMMENT ON COLUMN WFD_V_FLOW.ID IS '主键';
COMMENT ON COLUMN WFD_V_FLOW.INIT_AUTH_ID IS '发起权限';
COMMENT ON COLUMN WFD_V_FLOW.IS_LATEST IS '是否最新';
COMMENT ON COLUMN WFD_V_FLOW.IS_USED IS '是否已使用';
COMMENT ON COLUMN WFD_V_FLOW.MODEL IS '流程模型';
COMMENT ON COLUMN WFD_V_FLOW.NAME IS '流程名称';
COMMENT ON COLUMN WFD_V_FLOW.QUERY_AUTH_ID IS '查询权限';
COMMENT ON COLUMN WFD_V_FLOW.SORT_NO IS '流程序号';
COMMENT ON COLUMN WFD_V_FLOW.VERSION_BEGIN_DATE IS '版本生效日期';
COMMENT ON COLUMN WFD_V_FLOW.VERSION_END_DATE IS '版本失效日期';

CREATE TABLE WFI_FLOW
(
ID VARCHAR2(50) NOT NULL,
V_FLOW_ID VARCHAR2(50),
MODEL CLOB,
BUSINESS_KEY VARCHAR2(50),
FLOW_NO VARCHAR2(50),
FLOW_ID VARCHAR2(50),
FLOW_CODE VARCHAR2(50));
COMMENT ON TABLE WFI_FLOW IS '流程实例';
COMMENT ON COLUMN WFI_FLOW.BUSINESS_KEY IS '业务标识';
COMMENT ON COLUMN WFI_FLOW.FLOW_CODE IS '流程标识';
COMMENT ON COLUMN WFI_FLOW.FLOW_ID IS '流程id';
COMMENT ON COLUMN WFI_FLOW.FLOW_NO IS '工作文号';
COMMENT ON COLUMN WFI_FLOW.ID IS '流程实例id';
COMMENT ON COLUMN WFI_FLOW.MODEL IS '流程模型';
COMMENT ON COLUMN WFI_FLOW.V_FLOW_ID IS '流程发布id';


CREATE TABLE WFI_FLOW_USER
(
ID VARCHAR2(50) NOT NULL,
USER_ID VARCHAR2(50),
USER_TYPE INT NOT NULL,
FLOW_ID VARCHAR2(50),
TASK_ID VARCHAR2(50),
CREATE_TIME DATETIME(6),
IS_COMPLETED NUMBER(1,0),
REAL_NAME VARCHAR2(50));
COMMENT ON TABLE WFI_FLOW_USER IS '流程实例参与用户';
COMMENT ON COLUMN WFI_FLOW_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WFI_FLOW_USER.FLOW_ID IS '流程实例id';
COMMENT ON COLUMN WFI_FLOW_USER.ID IS '主键';
COMMENT ON COLUMN WFI_FLOW_USER.IS_COMPLETED IS '是否已完成';
COMMENT ON COLUMN WFI_FLOW_USER.REAL_NAME IS '用户名称';
COMMENT ON COLUMN WFI_FLOW_USER.TASK_ID IS '任务id';
COMMENT ON COLUMN WFI_FLOW_USER.USER_ID IS '用户id';
COMMENT ON COLUMN WFI_FLOW_USER.USER_TYPE IS '参与类型(0-主办人,1-协办人)';

alter table WFD_FLOW_CATEGORY add constraint PK_WFD_FLOW_CATEGORY primary key(ID);
alter table WFD_FLOW add constraint PK_WFD_FLOW primary key(ID);
alter table WFD_FLOW_AGENT add constraint PK_WFD_FLOW_AGENT primary key(ID);
alter table WFD_GLOBAL_RULE add constraint PK_WFD_GLOBAL_RULE primary key(ID);
alter table WFD_GLOBAL_VARIANT add constraint PK_WFD_GLOBAL_VARIANT primary key(ID);
alter table WFD_V_FLOW add constraint PK_WFD_V_FLOW primary key(ID);
alter table WFI_FLOW add constraint PK_WFI_FLOW primary key(ID);
alter table WFI_FLOW_USER add constraint PK_WFI_FLOW_USER primary key(ID);
alter table WFD_FLOW add constraint FK_WFD_FLOW_CATEGORY_ID foreign key(CATEGORY_ID) references WFD_FLOW_CATEGORY(ID) on delete set null with index;
alter table WFD_FLOW add constraint UK_WFD_FLOW_CODE unique(CODE,APP_ID);
alter table WFD_FLOW_AGENT add constraint FK_WFD_FLOW_AGENT_FLOW_ID foreign key(FLOW_ID) references WFD_FLOW(ID) on delete cascade with index;
alter table WFD_V_FLOW add constraint FK_WFD_V_FLOW_FLOW_ID foreign key(FLOW_ID) references WFD_FLOW(ID) on delete cascade with index;
alter table WFD_V_FLOW add constraint FK_WFD_V_FLOW_CATEGORY foreign key(CATEGORY_ID) references WFD_FLOW_CATEGORY(ID) on delete set null with index;
alter table WFD_V_FLOW add constraint UK_WFD_V_FLOW_FLOW_VERSION unique(FLOW_VERSION,FLOW_ID);
alter table WFI_FLOW add constraint UK_WFI_FLOW_FLOW_NO unique(FLOW_NO,FLOW_ID);
alter table WFI_FLOW_USER add constraint FK_WFI_FLOW_USER_FLOW_ID foreign key(FLOW_ID) references WFI_FLOW(ID) on delete cascade with index;
alter table WFI_FLOW_USER add constraint UK_WFI_FLOW_USER_USER_ID unique(USER_ID,TASK_ID);

create table WF_PROPERTY
(
	NAME VARCHAR2(50),
	VALUE VARCHAR2(50),
	DESCRIPTION VARCHAR2(50)
);
comment on table WF_PROPERTY is '流程属性';
alter table WF_PROPERTY add constraint PK_WF_PROPERTY primary key(NAME);