ALTER TABLE `wfi_user_task_state`
ADD COLUMN `FLOW_ID` VARCHAR(50) NULL COMMENT '流程实例id' AFTER `STATE`;

DELETE FROM WFI_FOCUSED_WORK WHERE FLOW_INSTANCE_ID NOT IN (SELECT ID FROM WFI_FLOW);

ALTER TABLE `wfi_focused_work`
ADD CONSTRAINT `FK_WFI_FOCUSED_WORK_FLOW_ID`
  FOREIGN KEY (`FLOW_INSTANCE_ID`)
  REFERENCES `wfi_flow` (`ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;


DELETE FROM WFI_USER_TASK_STATE WHERE FLOW_ID NOT IN (SELECT ID FROM WFI_FLOW);

ALTER TABLE `wfi_user_task_state` 
ADD CONSTRAINT `FK_WFI_USER_TASK_STATE_FLOW_ID`
  FOREIGN KEY (`FLOW_ID`)
  REFERENCES `wfi_flow` (`ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE `WFI_FOCUSED_WORK`
ADD COLUMN `LATEST_READ_TIME` DATETIME COMMENT '用户最新一次浏览流程的时间';

ALTER TABLE `WFI_FOCUSED_WORK`
ADD COLUMN `LATEST_READ_FLAG` INT NOT NULL  DEFAULT 1 COMMENT '最新一次浏览后是否有更新 0 否 1 是';