CREATE TABLE `WFD_USER_PAGE`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`USER_ID` VARCHAR(50) NOT NULL COMMENT '用户主键',
`WFD_ID` VARCHAR(50) NOT NULL COMMENT '流程定义主键',
`PAGE_SIZE` INT NOT NULL  DEFAULT 10 COMMENT '默认每页数量',
`ARG1` VARCHAR(50) COMMENT '预留属性1',
`ARG2` VARCHAR(50) COMMENT '预留属性2',
`ARG3` VARCHAR(50) COMMENT '预留属性3',
`PAGE_CODE` VARCHAR(50) COMMENT '默认流程页面标识',
PRIMARY KEY(`ID`))
COMMENT = '用户默认流程页面';

CREATE TABLE `WFI_USER_TASK_STATE`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`TASK_ID` VARCHAR(50) NOT NULL COMMENT '任务主键',
`USER_ID` VARCHAR(50) NOT NULL COMMENT '用户主键',
`STATE` VARCHAR(50) NOT NULL COMMENT '办理状态',
PRIMARY KEY(`ID`))
COMMENT = '用户任务办理状态';