DROP TABLE WFI_FLOW_USER CASCADE CONSTRAINTS;
create table WFI_DELIVER
(
	ID VARCHAR2(50 CHAR),
	DELIVER_INFO CLOB,
	FLOW_ID VARCHAR2(50 CHAR)
);
comment on table WFI_DELIVER is '流程-转交信息';
comment on column WFI_DELIVER.ID is '主键';
comment on column WFI_DELIVER.DELIVER_INFO is '转交信息';
comment on column WFI_DELIVER.FLOW_ID is '流程实例ID';
alter table WFI_DELIVER add primary key(ID);

ALTER TABLE WFI_DELIVER
 ADD CONSTRAINT FK_WFI_DELIVER_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;