CREATE TABLE WFI_V_FLOW
(
  ID                VARCHAR2(50 CHAR),
  FLOW_ID           VARCHAR2(50 CHAR),
  MODEL             CLOB,
  BPMN              CLOB,
  FLOW_VERSION      NUMBER,
  VERSION_END_DATE  DATE
);

COMMENT ON TABLE WFI_V_FLOW IS '流程实例版本';

COMMENT ON COLUMN WFI_V_FLOW.ID IS '主键';

COMMENT ON COLUMN WFI_V_FLOW.FLOW_ID IS '流程实例ID';

COMMENT ON COLUMN WFI_V_FLOW.MODEL IS '流程定义模型';

COMMENT ON COLUMN WFI_V_FLOW.BPMN IS 'BPMN模型';

COMMENT ON COLUMN WFI_V_FLOW.FLOW_VERSION IS '流程版本';

COMMENT ON COLUMN WFI_V_FLOW.VERSION_END_DATE IS '版本失效时间';



ALTER TABLE WFI_V_FLOW ADD (
  CONSTRAINT WFI_V_FLOW_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_WFI_V_FLOW_VERSION
  UNIQUE (FLOW_ID, FLOW_VERSION)
  ENABLE VALIDATE);

ALTER TABLE WFI_V_FLOW ADD (
  CONSTRAINT FK_WFI_V_FLOW_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);