CREATE TABLE WFI_BACKUP
(
  ID           VARCHAR2(50 CHAR),
  FLOW_ID      VARCHAR2(50 CHAR),
  DESCRIPTION  VARCHAR2(200 CHAR),
  VERSION      NUMBER,
  BACKUP_TIME  DATE,
  BACKUP_DATA  CLOB
);

COMMENT ON TABLE WFI_BACKUP IS '流程实例-备份信息';

COMMENT ON COLUMN WFI_BACKUP.ID IS '主键';

COMMENT ON COLUMN WFI_BACKUP.FLOW_ID IS '流程实例id';

COMMENT ON COLUMN WFI_BACKUP.DESCRIPTION IS '描述';

COMMENT ON COLUMN WFI_BACKUP.VERSION IS '版本';

COMMENT ON COLUMN WFI_BACKUP.BACKUP_TIME IS '备份时间';

COMMENT ON COLUMN WFI_BACKUP.BACKUP_DATA IS '备份数据';


ALTER TABLE WFI_BACKUP
 ADD (TASK_ID  VARCHAR2(50 CHAR));


COMMENT ON COLUMN WFI_BACKUP.TASK_ID IS '任务id';

ALTER TABLE WFI_BACKUP
 ADD (APP_ID  VARCHAR2(50 CHAR));


COMMENT ON COLUMN WFI_BACKUP.APP_ID IS '应用id';

ALTER TABLE WFI_BACKUP ADD (
  CONSTRAINT WFI_BACKUP_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_WFI_BACKUP_VERSION
  UNIQUE (FLOW_ID, VERSION, APP_ID)
  ENABLE VALIDATE,
  CONSTRAINT UK_WFI_BACKUP_TASK_ID
  UNIQUE (FLOW_ID, TASK_ID, APP_ID)
  ENABLE VALIDATE);

ALTER TABLE WFI_BACKUP
 ADD (ENGINE_VERSION  VARCHAR2(50 CHAR));


COMMENT ON COLUMN WFI_BACKUP.ENGINE_VERSION IS '流程引擎版本';
