CREATE TABLE WFI_FOCUSED_WORK
(
ID VARCHAR2(50 CHAR) NOT NULL,
USER_ID VARCHAR2(50 CHAR) NOT NULL,
FLOW_INSTANCE_ID VARCHAR2(50 CHAR) NOT NULL,
STARTER_ID VARCHAR2(50 CHAR),
START_TIME DATE,
WORK_NO VARCHAR2(50 CHAR) NOT NULL,
WFD_ID VARCHAR2(50 CHAR) NOT NULL,
WFD_CATEGORY_ID VARCHAR2(50 CHAR) NOT NULL,
APP_ID VARCHAR2(50 CHAR) NOT NULL,
CREATE_TIME DATE
);
COMMENT ON TABLE WFI_FOCUSED_WORK IS '已关注工作';
COMMENT ON COLUMN WFI_FOCUSED_WORK.APP_ID IS '应用ID';
COMMENT ON COLUMN WFI_FOCUSED_WORK.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WFI_FOCUSED_WORK.FLOW_INSTANCE_ID IS '流程实例主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.ID IS '主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.STARTER_ID IS '发起人主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.START_TIME IS '发起时间';
COMMENT ON COLUMN WFI_FOCUSED_WORK.USER_ID IS '用户主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.WFD_CATEGORY_ID IS '流程定义类别主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.WFD_ID IS '流程定义主键';
COMMENT ON COLUMN WFI_FOCUSED_WORK.WORK_NO IS '文号';

ALTER TABLE WFI_FOCUSED_WORK ADD (
  CONSTRAINT WFI_FOCUSED_WORK_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

alter table WFD_DELEGATE_WORK add (NODE_NAME  VARCHAR2(50 CHAR));
COMMENT ON COLUMN WFD_DELEGATE_WORK.NODE_NAME IS '步骤名称';
alter table WFD_DELEGATE_WORK add (FLOW_NO  VARCHAR2(50 CHAR));
COMMENT ON COLUMN WFD_DELEGATE_WORK.FLOW_NO IS '文号';
alter table WFD_DELEGATE_WORK add (WFD_ID  VARCHAR2(50 CHAR));
COMMENT ON COLUMN WFD_DELEGATE_WORK.WFD_ID IS '流程定义主键';
alter table WFD_DELEGATE_WORK add (WFD_CATEGORY_ID  VARCHAR2(50 CHAR));
COMMENT ON COLUMN WFD_DELEGATE_WORK.WFD_CATEGORY_ID IS '流程定义类别主键';