CREATE TABLE WFI_COMMENT
(
  ID                VARCHAR2(50 CHAR),
  COMMENT_USER_ID   VARCHAR2(50 CHAR),
  COMMENT_USER      VARCHAR2(30 CHAR),
  REPLY_COMMENT_ID  VARCHAR2(50 CHAR),
  FLOW_ID           VARCHAR2(50 CHAR),
  COMMENT_TIME      DATE,
  TASK_ID           VARCHAR2(50 CHAR),
  COMMENT_TEXT      VARCHAR2(400 CHAR),
  APP_ID            VARCHAR2(50 CHAR),
  REPLY_USER_ID     VARCHAR2(50 CHAR),
  REPLY_USER        VARCHAR2(30 CHAR),
  USER_TYPE         NUMBER
);

COMMENT ON TABLE WFI_COMMENT IS '流程实例-意见评论';

COMMENT ON COLUMN WFI_COMMENT.ID IS '主键';

COMMENT ON COLUMN WFI_COMMENT.COMMENT_USER_ID IS '评论人id';

COMMENT ON COLUMN WFI_COMMENT.COMMENT_USER IS '评论人';

COMMENT ON COLUMN WFI_COMMENT.REPLY_COMMENT_ID IS '回复评论id';

COMMENT ON COLUMN WFI_COMMENT.FLOW_ID IS '流程实例id';

COMMENT ON COLUMN WFI_COMMENT.COMMENT_TIME IS '评论时间';

COMMENT ON COLUMN WFI_COMMENT.TASK_ID IS '任务id';

COMMENT ON COLUMN WFI_COMMENT.COMMENT_TEXT IS '评论内容';

COMMENT ON COLUMN WFI_COMMENT.APP_ID IS '应用标识';

COMMENT ON COLUMN WFI_COMMENT.REPLY_USER_ID IS '被回复人id';

COMMENT ON COLUMN WFI_COMMENT.REPLY_USER IS '被回复人';

COMMENT ON COLUMN WFI_COMMENT.USER_TYPE IS '评论人身份(-1无关人员,0主办人,1协办人)';



ALTER TABLE WFI_COMMENT ADD (
  CONSTRAINT WFI_COMMENT_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);

ALTER TABLE WFI_COMMENT ADD (
  CONSTRAINT FK_WFI_COMMENT_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);