CREATE TABLE "WFD_DELEGATE_RULE"
(
"ID" VARCHAR2(50) NOT NULL,
"APP_ID" VARCHAR2(50) NOT NULL,
"DELEGATE_USER_ID" VARCHAR2(50) NOT NULL,
"PROCESS_NAME" VARCHAR2(50),
"USED_FLAG" NUMBER NOT NULL,
"START_DATE" DATE,
"END_DATE" DATE,
"CREATE_TIME" DATE,
"PROCESS_ID" VARCHAR2(50)) ;
COMMENT ON TABLE "WFD_DELEGATE_RULE" IS '委托规则';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."APP_ID" IS '应用ID';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."DELEGATE_USER_ID" IS '委托人主键';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."END_DATE" IS '有效期截止';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."ID" IS '主键';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."PROCESS_ID" IS '工作主键';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."PROCESS_NAME" IS '工作名称';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."START_DATE" IS '有效期起始';
COMMENT ON COLUMN "WFD_DELEGATE_RULE"."USED_FLAG" IS '是否启用，0否，1是';

CREATE TABLE "WFD_DELEGATE_USER"
(
"ID" VARCHAR(50) NOT NULL,
"RULE_ID" VARCHAR2(50) NOT NULL,
"USER_ID" VARCHAR2(50) NOT NULL,
"REAL_NAME" VARCHAR2(50) NOT NULL,
"CREATE_TIME" DATE
 );
COMMENT ON TABLE "WFD_DELEGATE_USER" IS '委托规则被委托人';
COMMENT ON COLUMN "WFD_DELEGATE_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "WFD_DELEGATE_USER"."ID" IS '主键';
COMMENT ON COLUMN "WFD_DELEGATE_USER"."REAL_NAME" IS '被委托人姓名';
COMMENT ON COLUMN "WFD_DELEGATE_USER"."RULE_ID" IS '委托规则主键';
COMMENT ON COLUMN "WFD_DELEGATE_USER"."USER_ID" IS '被委托人主键';

CREATE TABLE "WFD_DELEGATE_WORK"
(
"ID" VARCHAR2(50) NOT NULL,
"APP_ID" VARCHAR2(50) NOT NULL,
"USER_ID" VARCHAR2(50) NOT NULL,
"DELEGATE_USER_ID" VARCHAR2(50) NOT NULL,
"TASK_ID" VARCHAR2(50) NOT NULL,
"PROCESS_ID" VARCHAR2(50) NOT NULL,
"CREATE_TIME" DATE,
"TASK_NAME" VARCHAR2(50) NOT NULL,
"DELEGATE_REAL_NAME" VARCHAR2(50)) ;
COMMENT ON TABLE "WFD_DELEGATE_WORK" IS '委托工作记录';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."APP_ID" IS '应用ID';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."DELEGATE_REAL_NAME" IS '被委托人姓名';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."DELEGATE_USER_ID" IS '被委托人主键';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."ID" IS '主键';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."PROCESS_ID" IS '流程实例主键';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."TASK_ID" IS '任务主键';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."TASK_NAME" IS '任务名称';
COMMENT ON COLUMN "WFD_DELEGATE_WORK"."USER_ID" IS '委托人主键';

alter table WFD_DELEGATE_USER add constraint PK_WFD_DELEGATE_USER primary key(ID);
alter table WFD_DELEGATE_RULE add constraint PK_WFD_DELEGATE_RULE primary key(ID);
alter table WFD_DELEGATE_WORK add constraint PK_WFD_DELEGATE_WORK primary key(ID);

ALTER TABLE WFD_DELEGATE_USER
 ADD CONSTRAINT FK_WFD_DELEGATE_USER_RULE_ID
  FOREIGN KEY (RULE_ID)
  REFERENCES WFD_DELEGATE_RULE (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;



