ALTER TABLE WFI_USER_TASK_STATE
 ADD (FLOW_ID  VARCHAR(50 ));

DELETE FROM WFI_FOCUSED_WORK WHERE FLOW_INSTANCE_ID NOT IN (SELECT ID FROM WFI_FLOW);

ALTER TABLE WFI_FOCUSED_WORK ADD
  CONSTRAINT FK_WFI_FOCUSED_WORK_FLOW_ID
  FOREIGN KEY (FLOW_INSTANCE_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;

DELETE FROM WFI_USER_TASK_STATE WHERE FLOW_ID NOT IN (SELECT ID FROM WFI_FLOW);

ALTER TABLE WFI_USER_TASK_STATE ADD
  CONSTRAINT FK_WFI_USER_TASK_STATE_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;

alter table WFI_FOCUSED_WORK add (LATEST_READ_TIME TIMESTAMP);

alter table WFI_FOCUSED_WORK add (LATEST_READ_FLAG INT DEFAULT 1 NOT NULL);