DROP TABLE WFI_FLOW_USER CASCADE CONSTRAINTS;
create table WFI_DELIVER
(
	ID VARCHAR(50),
	DELIVER_INFO CLOB,
	FLOW_ID VARCHAR(50),
 CONSTRAINT "PK_WFI_DELIVER" PRIMARY KEY ("ID") );

ALTER TABLE WFI_DELIVER
 ADD CONSTRAINT FK_WFI_DELIVER_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;