CREATE TABLE WFI_TASK_PENDING
(
  ID         VARCHAR(50),
  TASK_ID    VARCHAR(50),
  FLOW_ID    VARCHAR(50),
  APP_ID     VARCHAR(50),
  USER_TYPE  INT,
  CREATE_TIME  TIMESTAMP,
  USER_ID     VARCHAR(50),
  NODE_ID     VARCHAR(50),
  FLOW_CODE     VARCHAR(50)
);

COMMENT ON TABLE WFI_TASK_PENDING IS '待办任务';

COMMENT ON COLUMN WFI_TASK_PENDING.ID IS 'id';

COMMENT ON COLUMN WFI_TASK_PENDING.TASK_ID IS '任务id';

COMMENT ON COLUMN WFI_TASK_PENDING.FLOW_ID IS '流程实例id';

COMMENT ON COLUMN WFI_TASK_PENDING.APP_ID IS '应用id';

COMMENT ON COLUMN WFI_TASK_PENDING.USER_TYPE IS '用户身份';

COMMENT ON COLUMN WFI_TASK_PENDING.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN WFI_TASK_PENDING.USER_ID IS '办理人id';

COMMENT ON COLUMN WFI_TASK_PENDING.NODE_ID IS '任务id';

COMMENT ON COLUMN WFI_TASK_PENDING.FLOW_CODE IS '流程标识';

ALTER TABLE WFI_TASK_PENDING
 ADD CONSTRAINT PK_WFI_TASK_PENDING
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE;

ALTER TABLE WFI_FOCUSED_WORK
 DROP CONSTRAINT FK_WFI_FOCUSED_WORK_FLOW_ID;
 
ALTER TABLE WFI_FOCUSED_WORK
MODIFY(WORK_NO VARCHAR(200));