CREATE TABLE WFI_COMMENT
(
  ID                VARCHAR(50),
  COMMENT_USER_ID   VARCHAR(50),
  COMMENT_USER      VARCHAR(30),
  REPLY_COMMENT_ID  VARCHAR(50),
  FLOW_ID           VARCHAR(50),
  COMMENT_TIME      TIMESTAMP,
  TASK_ID           VARCHAR(50),
  COMMENT_TEXT      VARCHAR(400),
  APP_ID            VARCHAR(50),
  REPLY_USER_ID     VARCHAR(50),
  REPLY_USER        VARCHAR(30),
  USER_TYPE         INT
);

ALTER TABLE WFI_COMMENT ADD
  CONSTRAINT WFI_COMMENT_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE;

ALTER TABLE WFI_COMMENT ADD
  CONSTRAINT FK_WFI_COMMENT_FLOW_ID
  FOREIGN KEY (FLOW_ID)
  REFERENCES WFI_FLOW (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;