CREATE TABLE WFI_BACKUP
(
  ID           VARCHAR(50),
  FLOW_ID      VARCHAR(50),
  DESCRIPTION  VARCHAR(200),
  VERSION      INT,
  BACKUP_TIME  TIMESTAMP,
  BACKUP_DATA  CLOB
);


ALTER TABLE WFI_BACKUP
 ADD (TASK_ID  VARCHAR(50));

ALTER TABLE WFI_BACKUP
 ADD (APP_ID  VARCHAR(50));

ALTER TABLE WFI_BACKUP ADD
  CONSTRAINT PK_WFI_BACKUP
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE;
ALTER TABLE WFI_BACKUP ADD
 CONSTRAINT UK_WFI_BACKUP_VERSION
  UNIQUE (FLOW_ID, VERSION, APP_ID)
  ENABLE VALIDATE;
ALTER TABLE WFI_BACKUP ADD
 CONSTRAINT UK_WFI_BACKUP_TASK_ID
  UNIQUE (FLOW_ID, TASK_ID, APP_ID)
  ENABLE VALIDATE;

ALTER TABLE WFI_BACKUP
 ADD (ENGINE_VERSION  VARCHAR(50));