server:
  port: 5050

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null
  profiles:
    active: @profileActive@
  application:
    name: push-server







