/**
  2019/09/27:修改集团三员管理
 */
ALTER TABLE `JARIACEPLAT`.`SYS_USER` MODIFY COLUMN `USER_TYPE` INT(10) DEFAULT 3 COMMENT '用户类型（0租户管理员,1集团管理员,11待激活的集团管理员,111未分配的集团管理员,2应用管理员,22待激活的应用管理员,222未分配的应用管理员,3普通用户）';

ALTER TABLE `JARIACEPLAT`.`SYS_USER_ADMIN_ORG` ADD (`IS_ACTIVATED`  INT(1)  DEFAULT 0 COMMENT '是否被激活，0没有，1是');
ALTER TABLE `JARIACEPLAT`.`SYS_USER_ADMIN_ORG` ADD (`ROLE_TYPE`  INT(10)  DEFAULT 0 COMMENT '角色类型（11集团系统管理员,22集团安全保密员,33集团安全审计员）');

delete from `JARIACEPLAT`.`SYS_AUTH` where `ID` in('5fc1b8842fa04faea8f39beb866fd111','5fc1b8842fa04faea8f39beb866fd112');
delete from `JARIACEPLAT`.`SYS_AUTH_ROLE_V` where `AUTH_ID` in ('5fc1b8842fa04faea8f39beb866fd111','5fc1b8842fa04faea8f39beb866fd112');

insert into `JARIACEPLAT`.`SYS_AUTH_ROLE` (`ID`,`AUTH_ID`,`ROLE_ID`,`SIGN`,`IS_REVOKE`,`CREATE_USER`,`CREATE_TIME`,`UPDATE_TIME`,`REMARK`) values ('12323fe2ef32403dbf9dc989d0651231', '5fc1b8842fa04faea8f39beb866fd511', 'sec', null, 0, null, null, null, null);
insert into `JARIACEPLAT`.`SYS_AUTH_ROLE_V` (`ID`,`AUTH_ID`,`ROLE_ID`,`SIGN`,`IS_REVOKE`,`CREATE_USER`,`CREATE_TIME`,`UPDATE_TIME`,`REMARK`,`LV_ID`) values ('67870485-0733-0000-B229-5ED50026EA82', '5fc1b8842fa04faea8f39beb866fd511', 'sec', null, 0, null, null, null, null, 'sec');


/**
  2019/09/28:修改应用三员管理
 */
ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_ORG` ADD (`IS_ACTIVATED`  INT(1)  DEFAULT 0 COMMENT '是否被激活，0没有，1是');
ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_ORG` ADD (`ROLE_TYPE`  INT(10)  DEFAULT 0 COMMENT '角色类型（111应用系统管理员,222应用安全保密员,333应用安全审计员）');

ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_APP` ADD (`IS_ACTIVATED`  INT(1)  DEFAULT 0 COMMENT '是否被激活，0没有，1是');
ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_APP` ADD (`ROLE_TYPE`  INT(10)  DEFAULT 0 COMMENT '角色类型（111应用系统管理员,222应用安全保密员,333应用安全审计员）');

ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_USER_GROUP` ADD (`IS_ACTIVATED`  INT(1)  DEFAULT 0 COMMENT '是否被激活，0没有，1是');
ALTER TABLE `JARIACEPLAT`.`SYS_AUTH_SCOPE_USER_GROUP` ADD (`ROLE_TYPE`  INT(10)  DEFAULT 0 COMMENT '角色类型（111应用系统管理员,222应用安全保密员,333应用安全审计员）');

delete from `JARIACEPLAT`.`SYS_AUTH` where `ID` in('67e1114e83214aeb8a3ec0a6822fd111','67e1114e83214aeb8a3ec0a6822fd112');
delete from `JARIACEPLAT`.`SYS_AUTH_ROLE_V` where `AUTH_ID` in ('67e1114e83214aeb8a3ec0a6822fd111','67e1114e83214aeb8a3ec0a6822fd112');

insert into `JARIACEPLAT`.`SYS_AUTH_ROLE` (`ID`,`AUTH_ID`,`ROLE_ID`,`SIGN`,`IS_REVOKE`,`CREATE_USER`,`CREATE_TIME`,`UPDATE_TIME`,`REMARK`) values ('12323fe2ef32403dbf9dc989d065rt78', '67e1114e83214aeb8a3ec0a6822fdd30', 'groupsec', null, 0, null, null, null, null);
insert into `JARIACEPLAT`.`SYS_AUTH_ROLE_V` (`ID`,`AUTH_ID`,`ROLE_ID`,`SIGN`,`IS_REVOKE`,`CREATE_USER`,`CREATE_TIME`,`UPDATE_TIME`,`REMARK`,`LV_ID`) values ('67870485-0733-0000-ghuy-5ED50026EA82', '67e1114e83214aeb8a3ec0a6822fdd30', 'groupsec', null, 0, null, null, null, null, 'groupsec');

ALTER TABLE `JARIACEPLAT`.`SYS_AUDIT_LOG` ADD (`GROUP_ID`  VARCHAR(50) COMMENT '操作针对的集团');
ALTER TABLE `JARIACEPLAT`.`SYS_AUDIT_LOG` ADD (`APP_ID`  VARCHAR(50) COMMENT '操作针对的应用');

/**
   用户角色历史数据主表
 */
CREATE TABLE `JARIACEPLAT`.`SYS_USER_ROLE_LV`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`USER_ID` VARCHAR(50) COMMENT '用户ID',
`VERSION` INTEGER COMMENT '版本号',
`CREATE_USER` VARCHAR(50) COMMENT '创建用户',
`CREATE_TIME` DATETIME(6) COMMENT '创建时间',
`IS_LATEST` INT(1) COMMENT '是否最新',
PRIMARY KEY(`ID`),
CONSTRAINT `FK_SYS_USER_ROLE_LV_USER` FOREIGN KEY(`USER_ID`) REFERENCES `JARIACEPLAT`.`SYS_USER`(`ID`) ON DELETE CASCADE
)
COMMENT = '用户角色历史数据主表';

/**
   用户角色历史版本数据
 */
CREATE TABLE `JARIACEPLAT`.`SYS_USER_ROLE_V`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`ROLE_ID` VARCHAR(50) COMMENT '角色ID',
`LV_ID` VARCHAR(50) COMMENT '主表ID',
PRIMARY KEY(`ID`),
CONSTRAINT `FK_SYS_USER_ROLE_V_LV` FOREIGN KEY(`LV_ID`) REFERENCES `JARIACEPLAT`.`SYS_USER_ROLE_LV`(`ID`) ON DELETE CASCADE
)
COMMENT = '用户角色历史版本数据';

CREATE TABLE `JARIACEPLAT`.`BD_JOB`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`NAME` VARCHAR(50) COMMENT '职务名称',
`SORT_INDEX` INT(10) COMMENT '排序号',
`DATA_VERSION` VARCHAR(50) DEFAULT 0 COMMENT '数据版本',
`GROUP_ID` VARCHAR(50) COMMENT '集团ID',
PRIMARY KEY(`ID`),
CONSTRAINT `FK_BD_JOB_GROUP_ID` FOREIGN KEY(`GROUP_ID`) REFERENCES `JARIACEPLAT`.`ORG_GROUP`(`ID`) ON DELETE CASCADE
)
COMMENT = '职务表';


CREATE TABLE `JARIACEPLAT`.`BD_POST`
(
`ID` VARCHAR(50) NOT NULL COMMENT '主键',
`NAME` VARCHAR(50) COMMENT '岗位名称',
`DEPARTMENT_ID` VARCHAR(50) COMMENT '所属部门主键',
`GROUP_ID` VARCHAR(50) COMMENT '所属集团主键',
`ORGANIZATION_ID` VARCHAR(50) COMMENT '所属业务单元主键',
`DATA_VERSION` VARCHAR(50) DEFAULT 0 COMMENT '数据版本',
`SORT_INDEX` INT(10) DEFAULT 0 COMMENT '排序号',
PRIMARY KEY(`ID`),
CONSTRAINT `FK_BD_POST_GROUP_ID` FOREIGN KEY(`GROUP_ID`) REFERENCES `JARIACEPLAT`.`ORG_GROUP`(`ID`) ON DELETE CASCADE ,
CONSTRAINT `FK_BD_POST_ORG_ID` FOREIGN KEY(`ORGANIZATION_ID`) REFERENCES `JARIACEPLAT`.`ORG_ORGANIZATION`(`ID`) ON DELETE CASCADE ,
CONSTRAINT `FK_BD_POST_DEP_ID` FOREIGN KEY(`DEPARTMENT_ID`) REFERENCES `JARIACEPLAT`.`ORG_DEPARTMENT`(`ID`) ON DELETE CASCADE
)
COMMENT = '部门岗位表';

